### ISSUE TITLE
How to change web UI HttpPort

### ISSUE THREAD

**Issue by obrienmd** [ChangemakerStudios/Papercut#100]
I see in issue https://github.com/ChangemakerStudios/Papercut/issues/86 that changing the "HttpPort" setting should change the port that the Web UI for Papercut runs on. However, I have the following in my settings:

```
<userSettings>
    <Papercut.Properties.Settings>
      <setting name="HttpPort" serializeAs="String">
        <value>1080</value>
      </setting>
...
```

And the HTTP interface continues to run on the default port (both when launched in the foreground, and as a service). Am I missing something?

**Comment by Jaben** [comment]
The setting is located in the Papercut.Service.json file.

```javascript
{
   HttpPort: 1080
}
```

**Comment by obrienmd** [comment]
Works great, thanks!
