### ISSUE TITLE
Papercut Service.json has binary data

### ISSUE THREAD

**Issue by brianlocke** [ChangemakerStudios/Papercut#101]
Current json file contains non-ascii characters and has no json configuration data in it.

**Comment by Jaben** [comment]
The file is empty but contains a byte-order mark: https://en.wikipedia.org/wiki/Byte_order_mark denoting the text file encoding.

Feel free to overwrite it with the JSON structure.

I need to fix this situation -- and it's on my short list. I'm going to convert the configuration to hjson: https://github.com/hjson/hjson-cs

**Comment by brianlocke** [comment]
Thank you for the clarification!
