### ISSUE TITLE
Failed to Delete Message

### ISSUE THREAD

**Issue by phillijw** [ChangemakerStudios/Papercut#103]
I just installed a few minutes ago (latest: 5.1.23) on Win10 Pro. I went into settings, changed port to 2525 and saved. Then I tried to delete the default "Welcome to Papercut!" message and received error "Failed to Delete Message -- Access to path C:\Program Files (x86)\Changemaker Studios\Papercut\Readme.eml' is denied."

![image](https://user-images.githubusercontent.com/467889/38113942-297b8ee8-336c-11e8-99fa-53f6becfbd89.png)

**Comment by jijiechen** [comment]
This is an expected behavior, please see https://github.com/ChangemakerStudios/Papercut/issues/91
