### ISSUE TITLE
Release notes in app are old

### ISSUE THREAD

**Issue by phillijw** [ChangemakerStudios/Papercut#104]
Release notes are from v4.5.0.0 in 2016

**Comment by Jaben** [comment]
Yeah, I need to deal with that. Thanks for the reminder.

**Comment by Jaben** [comment]
I have a solution is just add a more generic email with a link to release notes. Will modify.

**Comment by Tdue21** [comment]
I will take this one, if that's ok?

**Comment by Tdue21** [comment]
I was thinking of creating a markdown file with the release notes, and then a script of some sort to convert it to html and from there to an eml file.
How does that sound?

**Comment by Jaben** [comment]
This has been fixed in latest thanks to @Tdue21 !!!
