### ISSUE TITLE
Chocolatey Package

### ISSUE THREAD

**Issue by gep13** [ChangemakerStudios/Papercut#107]
Are you in a position to fix up the failed package submission for Papercut?

https://chocolatey.org/packages/papercut/5.1.19

Let us know if you have any questions.

**Comment by Jaben** [comment]
Looks like it's good once again.

**Comment by gep13** [comment]
Do you want to go back and fix the older version? Or would you like me to reject that package version?

**Comment by Jaben** [comment]
Thank you -- you can reject it.
