### ISSUE TITLE
Trojan in PapercutService.5.1.23.zip?

### ISSUE THREAD

**Issue by rgwood** [ChangemakerStudios/Papercut#109]
Hi,

When downloading [PapercutService.5.1.23.zip](https://github.com/ChangemakerStudios/Papercut/releases/download/5.1.23/PapercutService.5.1.23.zip) in Chrome (Win10 67.0.3396.62), the download fails because Chrome thinks "it might be a malicious, unwanted, or uncommon file".

[When I run the zip through VirusTotal](https://www.virustotal.com/en/file/8ee7512ffd062bbc84a4cb56d7e9e014c8f622e5362f7386b91669b77041b9b6/analysis/1528236973/), it's mostly OK but 1 service detects "Trojan.MSIL.Agent". Possible that this has been infected somehow?

I find Papercut really useful, thanks for developing it!

**Comment by Jaben** [comment]
Yeah, it sees the "library bundling" (https://github.com/Fody/Costura) and assumes it's a trojan. Lots of false positives, unfortunately.

The binaries are built and deployed from the cloud (AppVeyor). The virus would have to be there -- which I doubt.

You could always build locally and see if it still complains.

**Comment by Jaben** [comment]
Closing
