### ISSUE TITLE
Option to print the email is missing

### ISSUE THREAD

**Issue by abstractindia** [ChangemakerStudios/Papercut#11]
This is wonderful app. Just thinking if there is an option available to print the email. Sometime client's demand a printed copy for review during the development process.

**Comment by Jaben** [comment]
Thanks! Yeah, I don't currently have time to add this feature, but I've marked it up for grabs in case anyone wants to take a stab at it.

**Comment by Jaben** [comment]
Thanks to the Web UI @jijiechen created -- you should be able to print the emails easily in browser. Please try and let us know.
