### ISSUE TITLE
Relative urls for API calls.

### ISSUE THREAD

**Issue by jafin** [ChangemakerStudios/Papercut#116]
**Is your feature request related to a problem? Please describe.**
When deploying Papercut webUI behind a reverse proxy it would be easier to setup the proxy rules if all the paths used were relative.  The JS,CSS already are but the API endpoints are not.

**Describe the solution you'd like**
Change API endpoints to be relative.

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/ChangemakerStudios/Papercut/pull/115

**Comment by jijiechen** [comment]
Please follow the thread in the [pull request view](https://github.com/ChangemakerStudios/Papercut/pull/115)

Closing this issue.
