### ISSUE TITLE
"Delete All" emails button

### ISSUE THREAD

**Issue by TKharaishvili** [ChangemakerStudios/Papercut#120]
**Is your feature request related to a problem? Please describe.**
I often find myself wanting/needing to delete all emails. In order to do that currently you have to use a couple of keystrokes - `Ctrl+A` and `delete`. Papercut is a "mouse-driven" app, at least in my experience, and you have to switch to a keyboard and use both hands to achieve this, which if you do it frequently, can become quite annoying.

**Describe the solution you'd like**
I'd like to place a new "Delete All" button next to "Forward" and "Delete" buttons which would delete all emails.

P.S.
I can offer a pull request for this issue, if you guys agree with it.

**Comment by jijiechen** [comment]
At the moment, you can try these workarounds:

- Right click any message, and 'Open containing folder', Select all the `eml` files and delete all
- Open the web UI at `http://localhost:37408` in a web browser and use the delete all button on the page.
