### ISSUE TITLE
No messages mail in Papercut

### ISSUE THREAD

**Issue by arnoldkiti** [ChangemakerStudios/Papercut#121]
Hello,

I download the portable version of Papercut and uncompressed it in C:\xampp\htdocs\
I launch the papercut.exe and the welcome interface comming well.
I made the file test_sendmail.php with the following code 

[https://pastebin.com/GL0uTZ76](url)

This is a way I edit my php.ini file

`
[mail function]
; For Win32 only.
; http://php.net/smtp
SMTP = localhost
; http://php.net/smtp-port
smtp_port = 25

; For Win32 only.
; http://php.net/sendmail-from
sendmail_from = kitiarnold@gmail.com

; For Unix only.  You may supply arguments as well (default: "sendmail -t -i").
; http://php.net/sendmail-path
sendmail_path = ""C:\xampp\sendmail\sendmail.exe" -t"

; Force the addition of the specified parameters to be passed as extra parameters
; to the sendmail binary. These parameters will always replace the value of
; the 5th parameter to mail().
;mail.force_extra_parameters =

; Add X-PHP-Originating-Script: that will include uid of the script followed by the filename
mail.add_x_header = Off

; The path to a log file that will log all mail() calls. Log entries include
; the full path of the script, line number, To address and headers.
;mail.log =
; Log mail to syslog (Event Log on Windows).
;mail.log = syslog
`

So tell me why nothing comming in the papercut app ?
Where is my error ?

Best regards,
Lordaker.

**Comment by jijiechen** [comment]
Could you share the code you used to send mails?
