### ISSUE TITLE
Add "Papercut" to SMTP banner

### ISSUE THREAD

**Issue by jorrit** [ChangemakerStudios/Papercut#122]
I wanted to test my remote mail server using the well known telnet method (HELO/MAIL FROM/RCPT TO/DATA). Although the server seemed to respond fine no mail was sent. It wasn't until much later that I realized that I had this server mapped to localhost in my hosts file, I was actually talking to Papercut.

I would like to request a feature where Papercut advertises the program name at the start of the SMTP session in the `220` line such that it is easier to recognize that the SMTP server is Papercut.

**Comment by Jaben** [comment]
Okay with me 👍
