### ISSUE TITLE
Question regarding Fody

### ISSUE THREAD

**Issue by Tdue21** [ChangemakerStudios/Papercut#127]
**Is your feature request related to a problem? Please describe.**
I am wondering if Fody and Costura are not complicating things needlessly, as the application does not use Click-Once anymore. 
I get that there is a small advantage in shipping a single assembly, but as there are several others files anyway, the advantage kind of vanishes. 

**Describe the solution you'd like**
Remove the references to Costura.Fody and Fody, as well as removing the imports in the csproj file.

**Comment by Jaben** [comment]
Yeah, it can be removed now. Fody is excellent, though. But yeah, Costura is unnecessary.

**Comment by Tdue21** [comment]
I had gotten the impression that Fody was a huge part of what Costura did. I see that is not issue. My bad. :smile:

**Comment by Jaben** [comment]
We have to keep Costura until I get rid of the plugin architecture (which I'm planning on doing here soon).
