### ISSUE TITLE
Forward Emails to Loggers or Other Endpoints

### ISSUE THREAD

**Issue by knobdy** [ChangemakerStudios/Papercut#13]
I would like to use this to log incoming emails - or even forward them on as syslog messages - possible?

Purpose:
Alerts from WUG (as an example) sent to Splunk.

**Comment by Jaben** [comment]
A rule could be made that does this, sure.

Currently, Seq (getseq.net) is supported out of the box as a logging solution.

**Comment by knobdy** [comment]
What would the rule look like and where does one apply it?

**Comment by Jaben** [comment]
What kind of format would you expect the email to be converted to? Raw bytes? JSON?

**Comment by knobdy** [comment]
think syslog format as that's what I'm talking about - wanting to feed
Splunk.

**Comment by Jaben** [comment]
Still not sure what that means. Emails have a very complex structure (mime). A logger traditionally has a very basic structure: message, level, maybe properties. What would be desirable in the log?

**Comment by knobdy** [comment]
As I think I said in the original question/post, I'm dealing with a product that only wants to send alerts via email and I'm wanting to get syslog alerts. Generally speaking that would include time, source, subject and brief message. Would just need to strip out the header information (the complex parts) and provide the body of the message. 
I believe the app will at least allow us to layout the emails so that would be a fixed format and contain all of the fields we'd want/need. 

Sent from Outlook Mobile

    _____________________________
