### ISSUE TITLE
5.2.0 does not start

### ISSUE THREAD

**Issue by ChaseGrant** [ChangemakerStudios/Papercut#131]
**Describe the bug**
I removed the old Papercut (5.1.76) and installed the new one (5.2.0) and neither the GUI or service start. No icon in the tray and service immediately stops.

**To Reproduce**
1. Install Papercut 5.2.0
2. Try to launch it
3. Does not launch

**Expected behavior**
I expect the app to launch and the service to work.

**Desktop**
 - OS: Windows 10 1809 x64 Enterprise
 - Browser: Mozilla Firefox x64
 - Version: 64b14

**Comment by fredrikcarlbom** [comment]
I experience the same problem
**Desktop**
* Windows 10 1803 x64 Enterprise

Application: Papercut.exe

> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.IO.FileNotFoundException
>    at Papercut.App..ctor()
>    at Papercut.App.Main()

> Faulting application name: Papercut.exe, version: 5.2.0.0, time stamp: 0x5c040dee
> Faulting module name: KERNELBASE.dll, version: 10.0.17134.407, time stamp: 0x99042cc0
> Exception code: 0xe0434352
> Fault offset: 0x000000000003a388
> Faulting process id: 0x2aa4
> Faulting application start time: 0x01d48ae473cf022a
> Faulting application path: C:\Program Files (x86)\Changemaker Studios\Papercut\Papercut.exe
> Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
> Report Id: 862276b7-36b7-40f6-a9e0-539649789a2c
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by Jaben** [comment]
Taken down for now -- it's binding issues primarily.
