### ISSUE TITLE
German Umlauts not showed correctly

### ISSUE THREAD

**Issue by mstenz** [ChangemakerStudios/Papercut#132]
If I send a UTF-8 encoded email with German umlauts (äüö) this is only showed as ? in Papercut. also the .eml file itself contains the ? directly even if i open it with different programm (like Outlook). So I assume this is an issue while getting the email or storing them in the file locally.

**Comment by aplitax** [comment]
Same problem with Czech diacritics when email is send with UTF-8 encoding.

+1

**Comment by Jaben** [comment]
All: Please attach example EMLs that show the problem. I'm not German or Swedish -- and I unfortunately don't have access to simply create these types of examples.

**Comment by mstenz** [comment]
Here you can see a paste:
https://pastebin.com/09BxpGDb
the ??? in the E-Mail are the umlauts.

**Comment by aplitax** [comment]
In attachment is mail with text "Dobrý den, vaše objednávka byla přijata." in body. In Papercut is displayed as "Dobr? den, va?e objedn?vka byla p?ijata."
[20190131185552389-426b94.zip](https://github.com/ChangemakerStudios/Papercut/files/2818476/20190131185552389-426b94.zip)

**Comment by Jaben** [comment]
Thanks you for the EML file. Closing as it's a duplicate of #96.

**Comment by aplitax** [comment]
Thank you, now it works !!!
