### ISSUE TITLE
Service API for automated testing

### ISSUE THREAD

**Issue by Omzig** [ChangemakerStudios/Papercut#133]
**Is your feature request related to a problem? Please describe.**
I am unable to automate my testing using your application.

**Describe the solution you'd like**
Please give a service API, RESTful or .svc that allows other apps to hit your app.

**Describe alternatives you've considered**
I have created my own Server and API right now to solve this problem.

**Additional context**
The service should be able to basic things like:

- Get Email count

- Get Messages

- Clear All Mail

**Comment by Jaben** [comment]
Latest version makes this feature more discoverable.
