### ISSUE TITLE
Client attempts to start duplicate SMTP server over already running Papercut Service

### ISSUE THREAD

**Issue by Inzanit** [ChangemakerStudios/Papercut#134]
**Describe the bug**
When the Papercut SMTP service is running and the GUI is launched after the fact, especially when a machine is first turned on, the client takes upwards of around 15 minutes to start up. Once the GUI appears, an error is displayed to show it failed starting an SMTP service on the default port, 25, where the Papercut service is already running.

Changing the port of the Papercut client **does not** fix this.

Once the client has opened, and the error is dismissed, everything works fine and the background SMTP server continues to function - all emails are piped through localhost.

**To Reproduce**
1. Install Papercut, along with the SMTP service
2. Restart machine
3. Ensure the Papercut service is running
4. Start the Papercut client
5. Client takes 15-20 minutes to open, shows error dialog

**Expected behavior**
The GUI immediately (or with small delay) opens and doesn't attempt to start another SMTP server.

**Workaround**
Manually stopping the Papercut backend service, then starting the GUI, brings up the client **immediately**.

**Desktop (please complete the following information):**
 - OS: Windows 10 (Pro)
 - Browser: N/A
 - Version: 10.0.17763 (Build 17763)

**Additional context**
This happens on all machines in our office and is incredibly annoying. I understand this is _one of those_ bug reports that may not easily be reproducible, but I could submit a PR to at least bring up the GUI even if the client has not yet started the SMTP service, that or we use our own forked version of Papercut.

Having looked at the code, there seems to be an observable retry with a small timeout.

**Comment by Jaben** [comment]
I have it fixed -- but thanks to recent changes where Fody/Costura was removed, it requires me to rework the entire build and deployment/setup systems -- which I don't have time for right now.

So development is stuck until:

1. Fody/Costrua is put back
2. I redo all the builds/deployments/setups to support the contantly changing landscape of .NET and Core deployments.

Even if you submit a PR, I can't make a new release, is what I'm saying.

**Comment by Jaben** [comment]
I'll probably end up putting Costura back in as a ton of stuff is waiting for release.

**Comment by Jaben** [comment]
Please test latest release and re-open this issue if you are still having a problem.
