### ISSUE TITLE
Question: Where are received emails stored, is this configurable?

### ISSUE THREAD

**Issue by ericnewton76** [ChangemakerStudios/Papercut#135]
Just curious as to where emails are stored.

I just installed the app fresh, and see the "Welcome to Papercut!" email, which I tried to delete after reading.

I encountered an error right away (because Program Files isnt where data should be stored).

Now I'm wondering where it's going to try to store emails, and if its using Program Files for its storage, this is not a good solution.

If anything, a configurable option for where to store emails is preferred, with the default being within C:\ProgramData\Papercut

Love the program though... Just needed a mini smtp server to accept emails and let me view them reasonably well (plus, forward them to my project manager to see them).  Currently using mailslurper but it doesnt have that feature, and getting emails out of it is cumbersome.

**Comment by ericnewton76** [comment]
Sorry!  I see the log now, and its default is `%USERPROFILE%/Roaming/Papercut` which works fine.

**Comment by Jaben** [comment]
Closing.
