### ISSUE TITLE
How to disable Papercut auto start

### ISSUE THREAD

**Issue by nodermatt** [ChangemakerStudios/Papercut#136]
**Describe the bug**
Papercut service starts at windows startup which then blocks ports like 25 for XAMP (Mercury).

**To Reproduce**
1. Install Paperput
2. Install XAMP
3. Restart computer
4. Start XAMP and attempt to run MySQL

**Expected behavior**
Only have Papercut running when double-clicking the icon.

**Screenshots**
I can't find the service in Windows TaskManager in tab Startup, where usually services can be disabled
![image](https://user-images.githubusercontent.com/1467464/52037791-536fbb00-2530-11e9-91df-f15b05edae9b.png)

**Desktop (please complete the following information):**
- Windows 10

**Comment by Jaben** [comment]
Click options:

![image](https://user-images.githubusercontent.com/448726/52063118-f419a700-253f-11e9-8bc8-f4ae20e16ca7.png)

**Comment by Jaben** [comment]
You could also change the port in there as well.
