### ISSUE TITLE
Running Papercut.Service.exe from command line throws an Exception

### ISSUE THREAD

**Issue by Caltor** [ChangemakerStudios/Papercut#139]
**Describe the bug**
If you run Papercut.Service.exe from the command line then it throws the following exception.

> 2019-02-28T16:34:23.8147210Z Exception while emitting periodic batch from Serilo
> g.Sinks.Seq.SeqSink: System.Net.Http.HttpRequestException: An error occurred whi
> le sending the request. ---> System.Net.WebException: Unable to connect to the r
> emote server ---> System.Net.Sockets.SocketException: No connection could be mad
> e because the target machine actively refused it 127.0.0.1:5341
>    at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Sock
> et s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state,
> IAsyncResult asyncResult, Exception& exception)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, Tr
> ansportContext& context)
>    at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar
> )
>    --- End of inner exception stack trace ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
> ification(Task task)
>    at Serilog.Sinks.Seq.SeqSink.<EmitBatchAsync>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
> ification(Task task)
>    at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.<OnTick>d__16.MoveNext

**To Reproduce**
1. Open command prompt
2. >C:
3. >CD "\Program Files (x86)\Changemaker Studios\Papercut"
4. >Papercut.Service.exe
5. See the exception in the section above

**Expected behavior**
No exception

**Desktop (please complete the following information):**
 - OS: Windows Server 2008 R2
 - Browser: N/A
 - Version 

**Smartphone (please complete the following information):**
 - Version: v5.2.16 [2019-02-01]

**Comment by Jaben** [comment]
Check your Papercut.Service.json file and see if you have "SeqEndpoint" in that file.

If so, remove and restart the service -- that should clear up that exception.

**Comment by Caltor** [comment]
I don't have `SeqEndpoint` in that file. It is still default.

**Comment by Jaben** [comment]
Can you try on the latest release (5.5.1)? Thanks.

**Comment by Caltor** [comment]
Nailed it! Thanks. 😄
