### ISSUE TITLE
broken img links

### ISSUE THREAD

**Issue by Stephanevg** [ChangemakerStudios/Papercut#141]
Hi, just FYI to let you guys know that a lot of the imges on the main readme.md are broken

![image](https://user-images.githubusercontent.com/6302961/53939989-d0a0c980-40b4-11e9-9564-a24c50001c21.png)

Cheers

**Comment by Jaben** [comment]
Thanks for the heads-up! Github cached them for me and I didn't noticed. 

Fixed now.
