### ISSUE TITLE
cannot parse response

### ISSUE THREAD

**Issue by jims-1234** [ChangemakerStudios/Papercut#144]
This was partially working with version 5.3.x, but i upgraded it in the hope it would fix it..

wireshark reports:

```
HELO hostname.example.com
220 Papercut.Service v6.0.0.0 ESMTP ready
MAIL FROM: user@hostname.example.com
250 Hello hostname.example.com, haven't we met before?
RCPT TO: user2@hostname.example.com
501 , 4 retry(ies) remaining.
DATA
501 expected NOOP/RSET/QUIT/HELO/EHLO/MAIL, 3 retry(ies) remaining.
Date: 05/03/19 10:42 AM +00:00 (GMT+00:00)
501 expected NOOP/RSET/QUIT/HELO/EHLO/MAIL, 2 retry(ies) remaining.
From: user@hostname.example.com
Subject: test subjet
To: user2@hostname.example.com
501 expected NOOP/RSET/QUIT/HELO/EHLO/MAIL, 1 retry(ies) remaining.
Mime-Version: 1.0
X-Priority: 3
X-Mailer: Mailer by Oracle UTL_TCP
501 expected NOOP/RSET/QUIT/HELO/EHLO/MAIL, 0 retry(ies) remaining.
Content-Type: multipart/mixed; boundary="=_mixed 0052287A85256E75_="

This is a Mime message, which your current mail reader may not
understand. Parts of the message will appear as text. If the remainder

```

log only mentions:

> [10:49:01 INF] New SMTP connection from 0.0.0.0
> [10:49:01 INF] Completed SMTP connection from 0.0.0.0

**Comment by Jaben** [comment]
I'm not sure what you're asking for here -- what doesn't work? Can you be a bit more specific?

**Comment by jims-1234** [comment]
Hi Jaben, apologies, for the limited info. Issue is papercut doesn't accept this email, Microsoft Exchange does.

Note my client is not 100% compliant with the RFC, so understand if you don't want to "fix" this.

Firstly my client says hello before papercut, this may cause the rest of the conversation to fail..?

```
HELO hostname.example.com
220 Papercut.Service v6.0.0.0 ESMTP ready
MAIL FROM: user@hostname.example.com
250 Hello hostname.example.com, haven't we met before?
RCPT TO: user2@hostname.example.com
501 , 4 retry(ies) remaining.
```

Client then says from ..., and paper says hello.. :)

Client then says rcpt to .., and paper cut says 501, 4 retries remaining..

So not sure what the problem is, it maybe the client talking first, it may be lack of '<' in email address, it maybe something else?

As I say, this works with exchange, just not papercut..!

Cheers

James

**Comment by Jaben** [comment]
Now Papercut just uses SmtpServer 
(https://github.com/cosullivan/SmtpServer), now.

You'd have to pull request there.

**Comment by Jaben** [comment]
Let me know if this is still an issue.
