### ISSUE TITLE
Papercut crashes when a message has an EML file attached (content type 'message/rfc822')

### ISSUE THREAD

**Issue by martinw3** [ChangemakerStudios/Papercut#146]
**Describe the bug**
When you send a message with an '.EML' file attachment (with content type 'message/rfc822') to papercut, it crashes the app. It also crashes papercut on startup if such a message is present in the history. 

**To Reproduce**
1. Use papercut 5.5.0
2. send the attached sample .eml file to papercut and see it crash
3. Reopen papercut and it crashes again

Changing the content type from 'message/rfc822' to 'text/plain' in the sample file makes papercut load OK.

Sample .EML file:

[20190517091710202 test message cb9652.txt](https://github.com/ChangemakerStudios/Papercut/files/3190646/20190517091710202.test.message.cb9652.txt)

**Comment by Jaben** [comment]
Interesting. I'll take a look, thanks.
