### ISSUE TITLE
Running service under a non-admin/non-SYSTEM account

### ISSUE THREAD

**Issue by jimbobmcgee** [ChangemakerStudios/Papercut#151]
Just a note to say that, if running Papercut under a non-admin account (such as a Managed Service Account), it will not start the HTTP listener (and does not always log an error, despite the `catch` at [WebServer.cs](https://github.com/ChangemakerStudios/Papercut/blob/develop/src/Papercut.App.WebApi/WebServer.cs#L89).

The quickest fix is to run, from an Administrator command prompt:

    netsh http add urlacl url=http://+:37408/ user=DOMAIN\Username

...to give permissions for that user to start an `HttpListener` using that binding.  

If you have reconfigured to use a port other than 37408, substitute it into the `url=` portion of the command.

Perhaps this is something `Papercut.Service.exe install` could be coerced to do for you...?

**Comment by Jaben** [comment]
This is fixed by issue #160 -- and will be released this week.
