### ISSUE TITLE
Logs should not be written to Program Files

### ISSUE THREAD

**Issue by jimbobmcgee** [ChangemakerStudios/Papercut#153]
It is not a recommended practice to write program output to the Program Files directory, as it typically requires administrative privileges to write there.  

In the absence of a configurable location, Papercut should probably target ProgramData instead.

In the short-term, this is probably resolvable by changing instances of `Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Logs", ...)` with `Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), "Papercut\\Logs", ...)`.

In the longer-term, making this a configurable setting may be beneficial, but I can't tell if you can get access to the settings early enough to catch all the places where you may need to log.

Once a ProgramData-based location is established, it may be reasonable to store rules.json and settings.json there too, especially since they can be written by the desktop app, which can (and should) be run by non-admin users.

**Comment by Jaben** [comment]
Agreed. Needs to be changed.

**Comment by billrob** [comment]
Plus you can't delete the sample email without some jumping around.

**Comment by Jaben** [comment]
Try latest v5.7.0 -- this has been done.
