### ISSUE TITLE
Mark as read option

### ISSUE THREAD

**Issue by Jheronymus** [ChangemakerStudios/Papercut#19]
I know you don't want to build a full-on mail client, but some way to mark items as read/unread would be nice.
Sometimes I receive multiple errors at once and I have to click through the mails and look at their timestamp to see which are from the latest test. 
(subjects won't differ that much if you are testing the same thing a lott)

**Comment by Jaben** [comment]
Honestly, what I was thinking of doing is making Papercut.Service a SMTP/POP server -- then it's pretty easy to use a "real" email client for testing.

But, I'll add as a feature request.

**Comment by Jheronymus** [comment]
thanks. 
A bit off topic: What I really like about PaperCut is that you don't need any install rights. For the service you do. This makes PaperCut easy to use on remote servers where I don't have admin rights, but I can still do my tests.
I like the service for servers we control, so I do need to have an open RDP session while testing web apps.
