### ISSUE TITLE
Crash on JS error in mail

### ISSUE THREAD

**Issue by defcon84** [ChangemakerStudios/Papercut#22]
I have an email which uses document.querySelectorAll.
This function is not supported in the internal browser used by Papercut it seems.

If it doesn't crash immediately, restart Papercut.
To fix the crash, you have to delete the eml file in %AppData%\Papercut.

the email header:

> From: example test@example.com
> Date: Wed, 27 Jul 2016 11:50:48 +0200
> Subject: Testmail for querySelectorAll
> Message-Id: SC8BW9DOTYT4.3OG558UIEFW53@PC13
> To: example test@example.com
> MIME-Version: 1.0
> Content-Type: text/html; charset=utf-8
> Bcc: test@example.com

the email content:
`<!DOCTYPE html><html><head><title>Testmail for querySelectorAll</title></head><body>
Testmail for querySelectorAll.
<script>var nodeList = document.querySelectorAll('*');</script></body></html>`

The error:
![papercut js error](https://cloud.githubusercontent.com/assets/1416066/17171412/ec310b96-53f0-11e6-880e-57ca941c0de5.PNG)

**Comment by Jaben** [comment]
Yeah, not sure how to solve this problem -- it's already tough trying to "control" IE inside Papercut. But I'll look into it.
