### ISSUE TITLE
Email times are displayed in UTC; can it use local machine timezone instead?

### ISSUE THREAD

**Issue by lifenstein** [ChangemakerStudios/Papercut#24]
I'm using [SendEmail](http://caspian.dotconf.net/menu/Software/SendEmail) to send emails. That program records the time in UTC, but suffixes it with "+0000" in the headers, indicating what it is doing. Papercut displays this (including the +0000) as-is, although changing the display format. It would be great if this was translated to local time, according to what is set in locally on the machine where it's displayed.

**Comment by Jaben** [comment]
Yes, worth adding. Thanks for the request.
