### ISSUE TITLE
Question about Service and Client

### ISSUE THREAD

**Issue by ChrisLynchHPE** [ChangemakerStudios/Papercut#29]
Is there any way to have the Papercut Service run somewhere else in the environment, and have the client connect to it remotely?

**Comment by Jaben** [comment]
Currently, it's not supported. But under the covers there is no magic -- just a socket connection. That socket connection could be made with external systems. I'll add it as a feature request.

**Comment by Jaben** [comment]
We've implemented a WebUI in lue of this feature. It will allow remote viewing of a system's emails.
