### ISSUE TITLE
Allow rules to alter server response

### ISSUE THREAD

**Issue by jjbott** [ChangemakerStudios/Papercut#31]
It'd be nice if rules were implemented in a way that allowed them to change the server response to something besides "250 OK". That'd make it easier to test how programs respond to various errors.

For example, I'd like to test cases where the SMTP server rejects a message due to attachment sizes being too large. I tried implementing a new rule that would have the intended effect, but found that the rules can not alter the response

Edit: Obviously if I'm mucking in the code I can have it return anything I want, but it'd be nice if it was a built in feature of the rules

**Comment by Jaben** [comment]
Interesting idea. I'll see what I can do.

**Comment by rhelms** [comment]
Seconding this idea. 

Being able to have a Reject rule would be great. 

Perhaps similar to the Conditional Forward, there would be a Regex on the body, regex on the header and additionally, regex on the recipients (To, CC and BCC). And then there would be a configurable response, perhaps defaulting to a Recipient Not Found response (and whatever the special code is for that).
