### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by Wavesonics** [ChangemakerStudios/Papercut#33]
Annotations should support Java 8 to avoid warnings when used in projects that use Java 8

`Warning:Supported source version 'RELEASE_7' from annotation processor 'ie.stu.papercut.compiler.AnnotationProcessor' less than -source '1.8'`

**Comment by Jaben** [comment]
@Wavesonics I'm pretty sure you have the wrong project. Looks like you want this one? https://github.com/Stuie/papercut

**Comment by Wavesonics** [comment]
Haha you're right, sorry about that!
