### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by amuagarwal** [ChangemakerStudios/Papercut#35]
It's Really good to have web interface similar to windows interface. 

Why I am looking for it?
I am in need to have local smtp server with web interface to check the application mail which some time need interaction and as i not have any SMTP relay server so looking forward to have web interface which can be hosted in IIS or PHP and access Papercut service to see the mails from anywhere

**Comment by Jaben** [comment]
This is a pretty big job at this time. Can't say it's high on the list at the moment.

**Comment by jijiechen** [comment]
Hi all, we are recently working on the Web interface. 
Hopefully basic features will be available in weeks. I'll send PRs when we reach a reasonable milestone.

If you get any comments, or want to track the latest progress, you are always welcome to visit our fork at https://github.com/jijiechen/Papercut

**Comment by Jaben** [comment]
@jijiechen great start!

**Comment by Jaben** [comment]
@jijiechen has made this a reality. Closing!
