### ISSUE TITLE
Limit and sort sent emails list

### ISSUE THREAD

**Issue by blacksmoke26** [ChangemakerStudios/Papercut#39]
Is there a way to sort send email files list by date descending order?

I have 100s of email,  need some way to show latest X in list, (Max items can be defined in Options Panel, somewhere [Show max sent items] => [#, 0 = all])

Those killing features are still missing. :(

![image](https://cloud.githubusercontent.com/assets/425744/22811523/19bf7aa0-ef61-11e6-9a8f-058029742f53.png)

**Comment by Jaben** [comment]
4.7.0.1 has sort order, you can get it in the releases here: https://github.com/ChangemakerStudios/Papercut/releases/tag/4.7.0.1

It does not currently have a limit.

**Comment by Jaben** [comment]
Also, far be it for me to tell you how to live your life -- but you may want to try at least showing a minor bit of appreciation before requesting another person you've never met from another part of the world spend there time helping you instead of say, spending it with their children.

**Comment by blacksmoke26** [comment]
That's cool. Having feature like setting limit would be great!
