### ISSUE TITLE
Having multiple forwarding rules results in corrupt e-mails

### ISSUE THREAD

**Issue by McRegt** [ChangemakerStudios/Papercut#42]
Hi, 

We currently have the following rules configured for forwarding all received e-mails to four different people.

![image](https://cloud.githubusercontent.com/assets/6177851/23009741/f6223dba-f417-11e6-9c50-a84250305f37.png)

When using this configuration a range of malformations occur, the following are some that we have seen:

1. No content is received in the e-mail.

![image](https://cloud.githubusercontent.com/assets/6177851/23009924/fd07d6ca-f418-11e6-8e85-ea9d9bf3c711.png)

2. Content is only received partially / incorrect.

![image](https://cloud.githubusercontent.com/assets/6177851/23009876/b705a9a4-f418-11e6-81a7-b6f809d7cf4c.png)

3. Content is received corrupted.

![image](https://cloud.githubusercontent.com/assets/6177851/23009896/d1f0bc5e-f418-11e6-8d3d-10e875f46249.png)

A combination of these malformations is also possible and has also been seen. 

These malformations only happen when more than 1 forwarding rule is enabled. Whenever only a single rule is active the e-mails are received correctly, it doesn't matter which rule; as long as it's one.

Any idea on what's causing this behavior?

**Comment by Jaben** [comment]
Could you try again with the latest release? https://github.com/ChangemakerStudios/Papercut/releases/tag/4.8.0.1

**Comment by McRegt** [comment]
Hi Jaben,

We already have the latest version installed, but are still encountering the issues, sorry for not mentioning this in the first post. We've successfully replicated the problem in 4.5 and 4.6 as well. 

![image](https://cloud.githubusercontent.com/assets/6177851/23052366/f7fcc97a-f4d0-11e6-84d4-3ced62512955.png)

**Comment by Jaben** [comment]
Hmm, I cannot reproduce. Is there any way you can provide your rules.json file SANS passwords/ips (obviously) so I can attempt to recreate that way? Thanks.

**Comment by McRegt** [comment]
Sure, I've changed the extension to txt as json isn't supported by GitHub for uploading.

[rules.txt](https://github.com/ChangemakerStudios/Papercut/files/802732/rules.txt)
