### ISSUE TITLE
Possible malware or false positive indicated with 4.8.0.1

### ISSUE THREAD

**Issue by ferventcoder** [ChangemakerStudios/Papercut#45]
Howdy,
 We received a report of a possible malware in the latest version of the package you have at https://chocolatey.org/packages/papercut/4.8.0.1.

I will just copy in some text from the report: 

> Kaspersky anti-virus detects it and describes it as "Trojan.MSIL.Crypt.dayr"

I did a little investigation regarding this, with the original VirusTotal scans from Feb 16, 2017 which turned up no issues: https://www.virustotal.com/en/file/9b109d72e746f1794b1e43dfec8778b27fb6c7722ca87579acd5bc0ed53b1c21/analysis/ and https://www.virustotal.com/en/file/ffb1d9acaf4cef4d45cbefb68129c8a8c116d3da2ba1af1e08ded0908e631c8f/analysis/

And after receiving the report today, I reran the VirusTotal scans to see if the AV scanners are able to pick up anything additional since this was a month and a half ago. Still waiting on the results to come back from that.

Have you had any other reports of this kind of thing?

**Comment by ferventcoder** [comment]
Also following up with the reporter to ensure it's not a false positive of the shim that is generated.

**Comment by Jaben** [comment]
First I've heard of this. The release is created on appveyor. Not sure where an injection would happen. Fody is used to package up the assemblies into a single exe -- could trigger a false positive.

**Comment by ferventcoder** [comment]
Interesting. I am hoping that it is a false positive related to the shim. I've notified the user reporting this and if they want to provide any more information here, they will.

**Comment by Jaben** [comment]
Thanks Rob.

**Comment by Jaben** [comment]
Added 4.8.0.3 deployed directly from AppVeyor. Not sure what else I can do.

**Comment by ferventcoder** [comment]
Looks like it was the actual that was determined to be an issue. :/

And look what turned up on the VirusTotal rerun - https://www.virustotal.com/en/file/9b109d72e746f1794b1e43dfec8778b27fb6c7722ca87579acd5bc0ed53b1c21/analysis/

**Comment by ferventcoder** [comment]
If I had to guess, I would say maybe it was triggered by one of the dependencies you were using. Did you upgrade any since 4.8.0.1?

**Comment by ferventcoder** [comment]
Okay, looks like one commit is the difference? https://github.com/ChangemakerStudios/Papercut/compare/c4e63b5c9584c1ac3b7311d8a41b7aa4f0e310d6...33332c50a6a8e83020863557051876d13ed01166

**Comment by ferventcoder** [comment]
Nothing there lends itself into what may be wrong. Will wait to see what 4.8.0.3 VT scans turn up.

**Comment by Jaben** [comment]
k, so still flags the .exe -- but as a new piece of malware with a different name:

https://www.virustotal.com/en/file/69e4212e08169be3adccf278d9b7a84cd568cbf252601e7f7c03ccd26bd4aa6d/analysis/

**Comment by ferventcoder** [comment]
Feels like a false positive to me.

**Comment by Jaben** [comment]
Okay, I'm closing this for now. Thanks, Rob.
