### ISSUE TITLE
Papercut.Service.json Options

### ISSUE THREAD

**Issue by HarleeDavidson** [ChangemakerStudios/Papercut#46]
Nice job with this utility, well done!

Documentation says:

_If manual confiugration is needed, the configuration file for Papercut.Service can be found in the same directory as the Papercut.Service.exe. Papercut.Service.json contains the configuration with comments outlining options._

Looking for the options in the file, but the file is empty, both in the download and in the source.

More specifically, I'd like to set logging options for Seq. For example, server, port, log level, and api key.

Thank you!

**Comment by Jaben** [comment]
Ahh, good catch -- I'll have to add that back in. 

For reference, settings for seq should be this:

```json
{
  "SeqEndpoint": "http://localhost:5341",
  "SeqLogLevel": "Verbose"
}
```

**Comment by HarleeDavidson** [comment]
@Jaben ,

Thanks for the quick reply. Is there an option for API Key? We use this to tag events from different sources (applications).

Thanks!

**Comment by Jaben** [comment]
@HarleeDavidson -- You're very welcome.

The Seq plugin doesn't currently support the API key. But it would be rather simple to add here: https://github.com/ChangemakerStudios/Papercut/blob/develop/src/Papercut.Module.Seq/AddSeqToConfiguration.cs

A PR would be great. If not, I'll add to my list. Warning: my list is currently rather lengthy :)

**Comment by Jaben** [comment]
Latest now has support for the Seq Api Key. Closing this issue.
