### ISSUE TITLE
Find New Deployment model

### ISSUE THREAD

**Issue by mirhagk** [ChangemakerStudios/Papercut#47]
Microsoft [just announced the shutdown of codeplex](https://blogs.msdn.microsoft.com/bharry/2017/03/31/shutting-down-codeplex/) which is where papercut still uses the releases.

There are releases on github as well, but the clickonce releases aren't going to work by the end of the year.

**Comment by Jaben** [comment]
Well, I haven't thought about it yet. Open to suggestions.

**Comment by Jaben** [comment]
https://github.com/Squirrel/Squirrel.Windows seems promising...

**Comment by mirhagk** [comment]
Yeah you still have quite a bit of time until you absolutely have to worry about it, I just saw the notice and thought I'd mention.  (It goes read only in october)

I have heard good things about squirrel, the only problem is what about all the existing clickonce users. Ideally they should automatically upgrade to the next version.

I'm a complete noob when it comes to clickonce, but is it possible to use it to push an update that then enables updating through squirrel? That would be the ideal setup.

**Comment by jcoutch** [comment]
If you want to keep using ClickOnce, you could set up builds via Appveyor:
http://www.rahulpnath.com/blog/automated-clickonce-deployment-of-a-wpf-application-using-appveyor/

And just found this video on changing the ClickOnce Update url to point to a new location:
https://robindotnet.wordpress.com/2010/01/17/how-to-move-a-clickonce-deployment/

This way, you can get everyone migrated over well before the CodePlex shutdown, and it gives you a lot more time to decide how you want to handle deployments in the future.

**Comment by Jaben** [comment]
@jcoutch thanks for the links! Yeah, this might be the easier way in the short term.

**Comment by Tdue21** [comment]
I would volunteer to build an installer with WiX Toolset if you're interested?

**Comment by Jaben** [comment]
@Tdue21 that would be fantastic -- yes I would appreciate that. Between work, kids, housing projects and summer vacations -- I don't have much time right now.

**Comment by Tdue21** [comment]
Oh, don't I know THAT feeling! 😄

**Comment by Tdue21** [comment]
I believe the installer is complete.

**Comment by Jaben** [comment]
Yes -- please test the new installer which has a v5 release here: https://github.com/ChangemakerStudios/Papercut/releases
