### ISSUE TITLE
When Message Sort Order is 'Descending' the 'current' message always moves to bottom

### ISSUE THREAD

**Issue by dleffler** [ChangemakerStudios/Papercut#50]
If you've set the Message Sort Order to 'Ascending' the newest message is always at the bottom, so this anomaly doesn't appear. However, when you set the Message Sort Order to 'Descending' the 'current message is set to the bottom which is now the oldest message. Two times this is a problem is:
1) when you receive a new message and click on the notice to open Papercut to the new message
2) when you delete the newest message, it then selects the oldest message (bottom of list) instead of the next oldest (now the newest message)

**Comment by Jaben** [comment]
Yeah, that could stand to be ironed out. Thanks for the heads-up.
