### ISSUE TITLE
Kaspersky sees v4.8.0.3 Papercut.exe as Trojan.MSIL.Crypt.dgxp virus

### ISSUE THREAD

**Issue by jimbobmcgee** [ChangemakerStudios/Papercut#51]
As per title, attempting to download the v4.8.0.3 release zip file, Kaspersky reports Trojan.MSIL.Crypt.dgxp virus.  They are not the only vendor to do so.

Possibly a false-positive, but not one I am going to override.

VT is here: https://virustotal.com/en/file/5e75bf8f85d2f2b7057c2dee31c4a6b16d930f30b4fe7a8fe705dab3efe904dc/analysis/1494607516/

**Comment by Jaben** [comment]
Papercut used Fody Colstra package to bundle up the exe... unfortunately, some virus scanner think it's a trojan: https://github.com/Fody/Costura/issues/161

**Comment by jimbobmcgee** [comment]
@Jaben -  Is there any real *need* to embed DLLs in your executable, rather than providing a traditional MSI installation to folder?  I don't particularly see a need for Papercut to be a portable app...

**Comment by Jaben** [comment]
Noted.

**Comment by Jaben** [comment]
Closing for now as the issue appears to be resolved.
