### ISSUE TITLE
Subject encoding issue (UTF8)

### ISSUE THREAD

**Issue by yarecky1** [ChangemakerStudios/Papercut#56]
Am I missing some obvious thing or your application doesn't present mail subject in right encoding?

No matter what encoding parameter I setup in my application (UTF-8, ASCII, UNICODE) during mail sending in Papercut (in subject field) I see a question mark `?` in place where typical characters for my language should be. Example `ęóąśłżźćń`. Mail body with these characters is shown properly.

**Comment by Jaben** [comment]
Yeah, can you screen shot an example?

Seems okay here:

![image](https://cloud.githubusercontent.com/assets/448726/26755505/69b4ed98-485c-11e7-9ddd-dfb5c1286cb5.png)

**Comment by yarecky1** [comment]
Here it is - see the same text in body and in subject.

![obraz](https://cloud.githubusercontent.com/assets/28206604/26755623/23ff0772-4891-11e7-95f9-f9dde8d1a44a.png)

**Comment by Jaben** [comment]
I think it's how it's being sent rather than Papercut.

Here is my test code in .NET:

```csharp
using (var c = new SmtpClient("127.0.0.1", 25))
{			
	c.DeliveryFormat = SmtpDeliveryFormat.International;
	var mm = new MailMessage();
	mm.To.Add(new MailAddress("suzànne@hotmail.com", "Suzànne"));
	mm.To.Add("SomeoneAwesome@you.com");
	mm.Bcc.Add("Whomever@you.com");
	mm.From = new MailAddress("tina@turner.com", "Tina Turner");

	mm.Body = @"Lyrics to your new favorite song. Very Cool <a href=""http://yada5555.com/app/pages/tracking/trackclick.aspx?nid=101105002158069113090238180025171086185053047158&e=026132148126184225126027168024182076173041160248017135148071116092102090209215142169163147093251&url=http%3a%2f%2fns2.dev.yada%2fpages%2ftracking%2funsubscribe.aspx%3fe%3d026132148126184225126027168024182076173041160248017135148071116092102090209215142169163147093251%26sb%3dProvider_10%26nid%3d101105002158069113090238180025171086185053047158%26utm_medium%3demail%26utm_content%3dHellop%26utm_campaign%3dagain%22%3EUnsubscribe%3C"">link</a>
	the email content:
`<title>Testmail for querySelectorAll</title>
Testmail for querySelectorAll.

<script>var nodeList = document.querySelectorAll('*');</script>`			
	";
	mm.HeadersEncoding = Encoding.Unicode;
	mm.BodyEncoding = Encoding.UTF8;
	mm.IsBodyHtml = true;
	mm.SubjectEncoding = Encoding.UTF8;
	mm.Subject = string.Format("You're Simply the Best! suzànne ﻇﻇﻇﻇﻇ ThreadID: {0}", Thread.CurrentThread.ManagedThreadId);

	c.Send(mm);
}
```

**Comment by yarecky1** [comment]
And here is how I'm sending it. It's typical method. Nothing fancy. Before posting an issue I added in line 6 encoding information but it didn't help. This method is used in multiple places of my application and users have not issue when they receive mails. Papercut was recommended to me as a helpful tool and normally these `????` is not a big issue for me but it looks that something must be debugged (on my or your side)...

```
        Using mail = New MailMessage
            With mail
                .From = New MailAddress(MailSettings.MailFromAddress, MailSettings.MailFromName)
                .To.Add([to])
                .Subject = subject
                .SubjectEncoding = Text.Encoding.UTF8 '<==!!!
                .IsBodyHtml = True
                Dim html As AlternateView = AlternateView.CreateAlternateViewFromString(htmlBody, Nothing, "text/html")
                .AlternateViews.Add(html)
            End With

            Using smtp = New SmtpClient
                With smtp
                    .UseDefaultCredentials = MailSettings.SmtpUseDefaultCredentials
                    .Credentials = New Net.NetworkCredential(MailSettings.SmtpCredentialsUsername, MailSettings.SmtpCredentialsPassword)
                    .Host = MailSettings.SmtpHost
                    .Port = MailSettings.SmtpPort
                    .EnableSsl = MailSettings.SmtpEnableSsl
                    .Timeout = 20000
                End With

                Try
                    AddHandler smtp.SendCompleted, AddressOf SendMailAsyncCompleted
                    Await smtp.SendMailAsync(mail).ConfigureAwait(False)
                Catch ex As Exception
                    smtp.SendAsyncCancel()
                End Try
            End Using
        End Using
```

**Comment by Jaben** [comment]
Make sure and add HeadersEncoding = Encoding.Unicode;

**Comment by yarecky1** [comment]
Sorry... not working. I've already copied previous time all your code including encoding information for subject as it was the only one line which was missing in my code. But for a proof reason here below my code one more time with screenshot.

Added `.HeadersEncoding = Text.Encoding.Unicode` and `.Subject = "SPECIAL FOR PAPERCUT: ęóąśłżźćń ĘÓĄŚŁŻŹŃ"` just for you to be sure.

```
With mail
    .HeadersEncoding = Text.Encoding.Unicode '<======================
    .Priority = MailPriority.Normal
    .From = New MailAddress(MailSettings.MailFromAddress, MailSettings.MailFromName)
    .To.Add([to])
    If Not String.IsNullOrWhiteSpace(bcc) Then .Bcc.Add(bcc)
    .SubjectEncoding = Text.Encoding.UTF8
    .Subject = "SPECIAL FOR PAPERCUT: ęóąśłżźćń ĘÓĄŚŁŻŹŃ" '<======================
    '.Subject = subject
    .BodyEncoding = Text.Encoding.UTF8
    .IsBodyHtml = True
    Dim html As AlternateView = AlternateView.CreateAlternateViewFromString(htmlBody, Nothing, "text/html")
    .AlternateViews.Add(html)
End With
```

![obraz](https://cloud.githubusercontent.com/assets/28206604/26764145/6d568fd2-4961-11e7-9ff1-bfdaefacf403.png)

**Comment by yarecky1** [comment]
Finally I found the solution. Once again I rechecked your code and found out that you use `SmtpClient.SmtpDeliveryFormat = SmtpDeliveryFormat.International`. I added this line to my code and it started to work.

SMTP Delivery Format is available since .NET Framework 4.5 - after MSDN:

> International; - A delivery format where non-ASCII characters in the envelope and header fields used in the Simple Mail Transport Protocol (SMTP) for mail messages are encoded with UTF-8 characters. The extensions to support international e-mail are defined in IETF RFC 6530, 6531, and 6532.

> SevenBit - A delivery format using 7-bit ASCII. The traditional delivery format used in the Simple Mail Transport Protocol (SMTP) for mail messages.

See this link too: [https://stackoverflow.com/questions/19714558/does-smtpclient-support-international-email-addresses-idn-intl-email-in-net-4](url)

**Comment by behinenet** [comment]
Hello yarecky1 
can you please help me to receive unicode emails with papercut???
just like you  I see question marks

**Comment by yarecky1** [comment]
Hi,

See my answer above - there is solution for it. Quote below:

> Finally I found the solution. Once again I rechecked your code and found out that you use `SmtpClient.SmtpDeliveryFormat = SmtpDeliveryFormat.International`. I added this line to my code and it started to work.
> 
> SMTP Delivery Format is available since .NET Framework 4.5 - after MSDN:
> 
>     International; - A delivery format where non-ASCII characters in the envelope and header fields used in the Simple Mail Transport Protocol (SMTP) for mail messages are encoded with UTF-8 characters. The extensions to support international e-mail are defined in IETF RFC 6530, 6531, and 6532.
> 
>     SevenBit - A delivery format using 7-bit ASCII. The traditional delivery format used in the Simple Mail Transport Protocol (SMTP) for mail messages.
> 
> See this link too: https://stackoverflow.com/questions/19714558/does-smtpclient-support-international-email-addresses-idn-intl-email-in-net-4
