### ISSUE TITLE
Emails Duplicate when Running Papercut & Service

### ISSUE THREAD

**Issue by Jean-Paul76** [ChangemakerStudios/Papercut#57]
Hi

I'm running the latest version of the Papercut GUI and Service.

When opening the GUI all e-mails are shown twice (duplicated).

**Comment by Jaben** [comment]
Are you running the GUI and service in the same directory?

**Comment by Jean-Paul76** [comment]
Hi Jaben

At the moment, yes I am.

I have tried it in separate folders as well.
