### ISSUE TITLE
Wrong encoding for message body

### ISSUE THREAD

**Issue by petr-hendl** [ChangemakerStudios/Papercut#58]
My test email in UTF-8 encoding is wrong in the message body. I have seen #56 - the Subject and From fields are displayed properly, but in the message body there are still question marks. See attached message sent twice from the same application, once received by Papercut and once by another tool. The problem is obviously in receiving (and not displaying), because the file on the disk is wrong.

Screenshot: ![2017-06-20 17_15_55-papercut](https://user-images.githubusercontent.com/15941148/27340967-306e0870-55dc-11e7-8f33-46acf122b508.png)

Email source taken by Papercut: [Papercut.eml.txt](https://github.com/ChangemakerStudios/Papercut/files/1088651/Papercut.eml.txt)

Email source received by another tool: [TestMailServerTool.eml.txt](https://github.com/ChangemakerStudios/Papercut/files/1088654/TestMailServerTool.eml.txt)

**Comment by Jaben** [comment]
I'll make UTF8 the default connection encoding which makes more sense to me too.
