### ISSUE TITLE
PaperCut Does not show emails if running for a while

### ISSUE THREAD

**Issue by moojjoo** [ChangemakerStudios/Papercut#59]
Curious if anyone else has this problem.  I keep PaperCut running all the time (Love the Product).  However, if I go to click on emails it does display.  I have to exit and restart.

**Comment by Jaben** [comment]
You mean the notification stops working or the messages don't display at all?

What do you mean by "I go to click on emails it does display" -- it does show them?

**Comment by moojjoo** [comment]
The messages do not display when you click on them.

**Comment by Jaben** [comment]
Hmm. I haven't noticed this issue and I keep papercut running for long periods of time (work). A restart fixes it? Which OS are you running?

**Comment by moojjoo** [comment]
I do not think it is the PaperCut Product, I think it has something to do with our network and what the network admins do at night.  Please close the issue.

**Comment by Jaben** [comment]
oh, okay -- good to know!
