### ISSUE TITLE
Issue at High Volume

### ISSUE THREAD

**Issue by JarrodJ83** [ChangemakerStudios/Papercut#6]
Was using this during a load test I was doing as to not send actual emails out anywhere. It started throwing "The server response was: Syntax error, command unrecognized" exceptions after about 12k emails.

**Comment by Jaben** [comment]
Please provide the code for the load test.

**Comment by JarrodJ83** [comment]
The load test was for a notification system built for one our clients so it's not something I could simply send you. You should just be able to fire up LinqPad or create a console app that loops and sends emails until you experience the issue I would think. If needed I could provide you something like that.

**Comment by Jaben** [comment]
I'll try and take a look when I get a chance.

**Comment by programcsharp** [comment]
I've run into this as well. If you're sending a bunch of emails in a loop -- testing a broadcast, for example, problems arise far earlier that 1000s of emails. 10s or 100s of emails in a tight loop will do it.

Papercut UI will freeze, Explorer process will crash and restart. I'd assume this isn't an issue with the server itself, but probably how it displays feedback and the systray notifications in particular. Throttling new email notifications to 1 per second or even less might help here...

Happy to test a fix and/or look at code if you can point me in the right direction.

**Comment by Jaben** [comment]
@programcsharp I would suggest testing your assertion by setting up the Papercut.Service and just attempting to overload the server -- sans UI.

**Comment by Jaben** [comment]
I tested with the service and there is no issue with 1000+ emails. The UI is the problem -- so I updated the UI to better throttle a high velocity of inbound emails. I'll release the update here very soon.

**Comment by programcsharp** [comment]
Awesome!

**Comment by Jaben** [comment]
Closing this issue as I believe it's resolved in latest.
