### ISSUE TITLE
Update the Papercut hompage to indicate the latest installers are on GitHub

### ISSUE THREAD

**Issue by martillodecampo** [ChangemakerStudios/Papercut#61]
The Papercut page at http://papercut.codeplex.com/ says: "Moved source to GitHub. Releases will stay on Codeplex due to ClickOnce." The "current" download the CodePlex page is v4.5 dated March 2016. 

It looks like the current product description and installers are on now GitHub. It might be best to remove everything from CodePlex and only leave a message directing people to GitHub.

**Comment by Jaben** [comment]
Done!
