### ISSUE TITLE
Changes in Service's Configuration doesn't apply while Client is running 

### ISSUE THREAD

**Issue by cincauhangus** [ChangemakerStudios/Papercut#64]
If you were to make a change in Papercut.Service.json and restarted the service while a papercut client is running, the new changes do not take effect and instead is overwritten by the client's cached configuration.

I'm running on Win 2012R2, Papercut 4.8.0, both running in separate folders.

**Comment by Jaben** [comment]
Yeah, that's working as designed as changes to the configuration are handled by the client if it's running.

**Comment by Jaben** [comment]
If you can provide more information into the use case, I'll look at modifying.
