### ISSUE TITLE
Open containing folder and highlight particular email

### ISSUE THREAD

**Issue by grokky1** [ChangemakerStudios/Papercut#69]
When I need to mess around / edit an email, I right click and choose "Open containing folder". However that shows me all the emails, which have guids for filenames. So I can't easily find the one I need without opening lots of them randomly until I find the correct one.

Would be better if it behaved in the expected way, which is that if I highlight an email and then "Open containing folder", it will 1) open the folder and 2) select that email in the folder list.

**Comment by Tdue21** [comment]
Currently the "Open containing folder" supports multiple files. If there are multiple folders an explorer view will open for each directory. 
However, no files are selected (obviously), and the current method is a bit at odds with this feature request. 
The functionality itself it a no-brainer to implement, but how to handle multiple files in the same folder? 
Should the function only support a single file, or should it select all relevant files? 
The latter may complicate things somewhat...
