### ISSUE TITLE
Automatically reload file system data

### ISSUE THREAD

**Issue by majkinetor** [ChangemakerStudios/Papercut#70]
I am using papercut for automated testing and the first thing I do when starting a test is `rm $env:APPDATA\Papercut\*`. In that case papercut still shows stale data (until restarted).

It would be good to have this among options.

**Comment by Jaben** [comment]
Hmm, that works perfectly for me. I can delete the whole directly and even undo the delete and Papercut UI reflects those changes.

**Comment by majkinetor** [comment]
It doesn't happen any more.
