### ISSUE TITLE
Assembly versions and file versions

### ISSUE THREAD

**Issue by Tdue21** [ChangemakerStudios/Papercut#71]
I realize that there haven't been much of a need before, but with the installer I made, maybe a few changes to the versioning is required. 
It is strictly speaking not necessary to do anything about the files, as it is only necessary for the installer, but since MSI only looks at the first three numbers, then 5.0.0.x will not cut it anymore.

The easiest fix will be to just move the build number up to the third position: 5.0.x.0.
This way, the MSI package will automatically uninstall the previous version before installing a new one. 

I would recommend that the file versions changed as well though. I believe this can be done automagically be AppVeyor, but I am uncertain as to how much is defined in the yml file and what is defined in the settings. 

I am thinking that it may be beneficial to pull everything into the yml file and thus foregoing any setup on AppVeyor. This way everything about any given build is source controlled. 

What do you think?

**Comment by Jaben** [comment]
Yeah, I'll modify the appveyor version and move it to increment minor.
