### ISSUE TITLE
The size of WebUI assembly file is large

### ISSUE THREAD

**Issue by jijiechen** [ChangemakerStudios/Papercut#72]
Hi Jaben,

I realize the file size of WebUI plugin is large, and this scenario improved the installer size a lot. It seems the root case is the WebUI assembly file is packing some redundant assembly files in it (e.g. Papercut.Core.dll ). These assembly files are not necessary for the WebUI plugin to reference & pack again since they are already referenced by the entry point assemblies.

I tried to exclude unnecessary files in a previous commit 09589a5a, but it seems you changed the `FodyWeavers.xml` in commit [4061cfd "Upgrade to .NET v4.5 -- leaving the past behind. WebAPI layer is properly loading now."](https://github.com/ChangemakerStudios/Papercut/commit/4061cfd2bc227c246af9abab07f7461ee233ab71) to fix something else. 

To solve the size issue, I'm considering if we can add the `IncludeAssemblies` Fody configuration back or do something else. So could you share more detail on the WebAPI layer loading issue you ran into at that time? Therefore I'll get a better idea for the size issue.

**Comment by Jaben** [comment]
Yeah, I removed it because it was causing loading errors (System.Net.Http, I believe). I think we just need to make sure all dependencies are referenced.

**Comment by jijiechen** [comment]
Will try to find other ways for merging assemblies in the future.
