### ISSUE TITLE
Convert Papertcut UI to Electron

### ISSUE THREAD

**Issue by Jaben** [ChangemakerStudios/Papercut#77]
Also requires .NET core conversion.

**Comment by Jaben** [comment]
What are your thoughts, @jijiechen ?

**Comment by jijiechen** [comment]
Thank you for asking.
I like the idea!

I do think Electron is a better solution for getting cross platform.
Additionally, I'm a fan of .NET Core, and I've been trying to port Papercut core project to .NET core runtime in the past weekend. You can take a gimps at here: https://github.com/jijiechen/PapercutCore
The main assemblies can now be compiled successfully and messages can be handled in a .NET core process!

**Comment by Jaben** [comment]
I saw that! Exciting!

I'll add .NET Core feature branch to this repo. You are welcome to work directly on it as I've given you organizational access.

**Comment by jijiechen** [comment]
Thank you so much.
I still need to find a way to share code between .NET Core runtime and .NET Framework runtime, so that we only maintain one code base and have both assemblies generated. I'll merge these change to this repo as soon as a basic milestone is ready.

**Comment by jijiechen** [comment]
Working on this.
Ran into many edge and dynamic assembly loading related issues, need help.

**Comment by Jaben** [comment]
Just loaded it up and it works good for me. I realize there is a lot more to do -- but wonderful progress so far, @jijiechen !

**Comment by jijiechen** [comment]
Right, there is much work to do.
And I also concern on the will-be size of redistribution archive package. The pre-built binary of Electron v1.6.2 itself is 50MB.

**Comment by jijiechen** [comment]
@Jaben 
You can track latest progress on the [Project view](https://github.com/ChangemakerStudios/Papercut/projects/1), I'll try to make it updated in time.

**Comment by Jaben** [comment]
@jijiechen yeah there is almost nothing that can be done about the size: https://github.com/electron/electron/issues/588

I do like the idea of a 'stripped down' headless release that just supports HTTP access -- the UI release would be for the desktop experience only.

**Comment by jijiechen** [comment]
Great! 
In the next release, there will be several kinds of releases:

1. Downloadable Binary for Papercut.Service
1. Docker/choco/brew installable packages
1. Downloadable desktop experience electron based app


Does this seem good?

**Comment by Jaben** [comment]
@jijiechen Yes! 

This is looking like an interesting initiative: https://github.com/pojala/electrino

**Comment by Jaben** [comment]
Suggestions?

On April 22, 2018 6:17:55 AM Sebastiaan Dammann <notifications@github.com> 
wrote:
I do think Electron is a better solution for getting cross platform.
That is questionable, there are other cross-platforms UI solutions being 
developed for .NET Core.

**Comment by Sebazzz** [comment]
I believe Avalonia UI is very viable: https://github.com/AvaloniaUI/Avalonia

**Comment by Tdue21** [comment]
Without having much idea about the options presented here, I feel Avalonia would be the better choice, rather than Electron. 

Personally I do not get the need to be cross platform anyway :)
