### ISSUE TITLE
.NET Core Conversion

### ISSUE THREAD

**Issue by Jaben** [ChangemakerStudios/Papercut#78]
Convert all except the WPF UI to .NET Core.

Feature Branch here:

https://github.com/ChangemakerStudios/Papercut/tree/feature/netcore

**Comment by jijiechen** [comment]
Got it.
So we are going to build a cross platform and container compatible version?

**Comment by Jaben** [comment]
Yes. 👍 That would be excellent.

**Comment by jijiechen** [comment]
I've created [a card](https://github.com/ChangemakerStudios/Papercut/projects/1#card-4802757) on the project view.

There are two strategies to provide .NET Core  compatibility:  
1. Only provide .NET standard based for foundation assemblies, provide platform-specific implementation for entry point assemblies in case of need. According to [.NET Core versions](https://github.com/dotnet/standard/blob/master/docs/versions.md) documentation, Full .NET Framework has shipped .NET Standard.
2. Make assemblies in all layers be .NET Core/Full .NET compatible, use conditional compilation directives to share code between context, and redistribute different binaries for each runtime.


Which one do you prefer? @Jaben

**Comment by Jaben** [comment]
@jijiechen 

#2 seems like a hassle and is more required for libraries.

Path #1 seems better for an application -- as it simplifies builds, etc. And it require any additional dependencies on the target machines, correct?

**Comment by jijiechen** [comment]
Indeed. In the latest **netcore** branch, I've implemented an electron app which uses .NET Standard based assemblies using the [electron-edge](https://github.com/kexplo/electron-edge) project.
For the WPF-based Papercut.UI project, I took it out temporarily from the solution file. We can take about it further on it later.

**Comment by Jaben** [comment]
This is done.
