### ISSUE TITLE
Use Papercut in automated testing

### ISSUE THREAD

**Issue by ericlovetocode** [ChangemakerStudios/Papercut#82]
I suppose Papercut doesn't support retrieving emails via IMAP/POP or REST API. Is that correct? I want to use Papercut in automated testing to confirm the email recipients and the content of the email. It may sound extreme. Would be nice if it can be done.

**Comment by jijiechen** [comment]
Hi @ericlovetocode  in the latest version, there is a Web UI available which consumes HTTP API exposed by the Web UI plugin.
Although it's not advised, you can use the HTTP APIs to achieve your requirements. Note that these APIs are not published or documented, so they may be modified in future releases.

Following APIs are available:
- List all messages:    `GET /api/messages`
- Load message detail:   `GET /api/messages/{id}`

Default port for the Web UI is `37408`, and you can configure it using `HttpPort` in the configuration file.
For instance, if you run Papercut locally, just visit `http://localhost:37408/api/messages`

**Comment by ericlovetocode** [comment]
Works beautifully! Thanks!
