### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by jgonyea** [ChangemakerStudios/Papercut#83]
Would you consider an option to run papercut in a portable fashion, something akin to the PA suite (https://portableapps.com/)?  I'd love it if I could run the app and have all its configuration and related files live within a single folder.  Thanks in advance either way.

**Comment by jgonyea** [comment]
Just checking to see if there's any thoughts on a portable version. Thanks.

**Comment by Jaben** [comment]
I wish Github had feature requests with Up/Down votes.

**Comment by jijiechen** [comment]
@Jaben You may use the thumb up and thumb down reactions 😄

**Comment by ericnewton76** [comment]
> I wish Github had feature requests with Up/Down votes.

I wish Github itself had feature requests for Github itself as well... lol

**Comment by jgonyea** [comment]
Closing request due to lack of activity
