### ISSUE TITLE
Application name conflicts with PaperCut

### ISSUE THREAD

**Issue by bryan5989** [ChangemakerStudios/Papercut#84]
There's a product by Ricoh called PaperCut, that we use in our org, and this smtp program is awesome but causes confusion when we talk about it in the office. -> https://www.papercut.com/ 

Any chance, there'll be a an awesome-er name soon?

**Comment by Jaben** [comment]
Hmm. Suggestions?

**Comment by bryan5989** [comment]
Still thinking. Everything I think of is lame.



On Oct 17, 2017 7:04 PM, "Jaben Cargman" <notifications@github.com> wrote:

Hmm. Suggestions?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChangemakerStudios/Papercut/issues/84#issuecomment-337402433>,
or mute the thread

**Comment by Jaben** [comment]
FauxMailer is the only thing I've come up so far.

**Comment by bryan5989** [comment]
NotAnotherMailServer-NAMS

NotMail

ToMailOrNotToMail

Do Not Send

Chain Breaker

Chain Breaker Extreme

Mail Hole

Dead Letter Office

Lazy Mail

Lazy Mail Server

No Mail For U

**Comment by RedRoyalDog** [comment]
Hello, I work for the same organization as Bryan5989. I'm actually the developer there. Love this software, however I agree. Confuses the hell out of our CIO. I would love to just call this The Awesome Lightweight Mails. However, you know..

**Comment by kasparspr** [comment]
May I suggest you first of all - to leave "Papercut" as is but add some prefix or suffix to this word?
Preferably suffix. For example "Papercut Mail" or "Papercut SMTP" or something like that.

**Comment by bryan5989** [comment]
Hadnt considered before but i concede that's a reasonable suggestion.

**Comment by Jaben** [comment]
@kasparspr I like Papercut Mail. Changing the whole application name seems a bit sudden considering how many people use the app and like the name (140k downloads!)

**Comment by jorrit** [comment]
Localpost? (as a reference to Localhost)

**Comment by Jaben** [comment]
Suggestions from my coworker: Origami or Origami Mail

I looked around and there is one: "Origami Studio" which is a MacOS mockup type app.

**Comment by ericnewton76** [comment]
TBH even Papercut is odd, the first time I installed it, I couldn't remember the name of it because it had no smtp/email/etc keywords in the title.

MockMail or FauxMail FauxSmtp or similar will work better and makes it more aptly named.

**Comment by Jaben** [comment]
Renamed to "Papercut SMTP" in v.5.7.0. I still have a bit more work to do (e.g. renaming the repository) -- but you'll notice the changes through most of the app.
