### ISSUE TITLE
How do you access the web interface

### ISSUE THREAD

**Issue by nSwann09** [ChangemakerStudios/Papercut#86]
Hi, 

I've downloaded and run the installer, and chose to install the web UI.

What do I need to do to start the webUI? How is it configured?

**Comment by jijiechen** [comment]
Hi @nSwann09  by default, you can access it using this URL: `http://localhost:37408`
You can also configure the `HttpPort` in the configuration file.

**Comment by ChrisLynchHPE** [comment]
I just upgraded from Paperclip 4.5 to 5.0, and I too had a hard time understanding how to access the new UI.  While I see `paperclip.exe` in Task Manager, I don't see a desktop UI.  I can only access the WebUI.  Does the desktop UI/app no longer work or is available?

**Comment by ChrisLynchHPE** [comment]
After I looked at some of the config files, it looks like the default is for the Paperclip.exe process to start hidden.  I changed:

``XML
      <setting name="RunOnStartup" serializeAs="String">
        <value>False</value>
      </setting>
```

to

```XML
      <setting name="RunOnStartup" serializeAs="String">
        <value>True</value>
      </setting>
```

And now the desktop app UI launched correctly.  Why is this hidden?  Why is it set to `False`?  Is it to move people to the WebUI?  If so, then there really should be some document informing those moving to newer versions.
