### ISSUE TITLE
Main papercut screen still lists codeplex url at the bottom

### ISSUE THREAD

**Issue by AlwaysTinkering** [ChangemakerStudios/Papercut#87]
The main PaperCut message list screen still shows the codeplex URL at the bottom.  Should this be updated to the new home on GitHub?  It will no longer be possible to update anything on codeplex after Nov 6.

It looks changed in the MainView.xaml file, but if so, it didn't make it into a published release yet.

**Comment by jnm2** [comment]
Also, I just installed 5.0.9 and it says 5.0.0 right above the codeplex link.

**Comment by Jaben** [comment]
Thanks for the report -- I'll fix.

**Comment by Jaben** [comment]
Fixed in latest.
