### ISSUE TITLE
forwarding messages to an SMTP server on a port other than 25

### ISSUE THREAD

**Issue by barsh** [ChangemakerStudios/Papercut#89]
Is there a way to specify the SMTP server port when forwarding messages?

![image](https://user-images.githubusercontent.com/2644202/32907012-51cfbdbc-cac4-11e7-9f1e-10593045a0b0.png)

**Comment by jijiechen** [comment]
Did you try add port after the server IP with a colon like this?  `127.0.0.1:2525`
If this does not work, I think `Papercut` does not support at the moment.

**Comment by Jaben** [comment]
Not complicated to fix -- but yes, it's not supported at the moment.
