### ISSUE TITLE
Crashing on Win7 with .NET framework v4.7.1!

### ISSUE THREAD

**Issue by kasparspr** [ChangemakerStudios/Papercut#90]
Papercut worked like a charm before...

Today after .NET framework update from 4.7 to 4.7.1 papercut.exe client constantly crashed on application startup. 
(however service worked ok)

Windows Eventlog logged unhandled exceptions like "**System.IO.FileFormatException at MS.Internal.FontFace.CompositeFontParser...**". Google search results led me to [Microsoft forum record](https://social.msdn.microsoft.com/Forums/en-US/a2dadbfc-475d-4409-ac1c-1c34f9e22607/compositefontparser-fail-after-installing-net-framework-update?forum=clr) and sequentially to [this dotnet announcement](https://github.com/dotnet/announcements/issues/53).

Uninstalling 4.7.1 and installing 4.7 helped!

**Comment by Jaben** [comment]
boo! Thanks for finding that, though!

**Comment by Jaben** [comment]
Duplicate issue in #92

**Comment by Jaben** [comment]
Closing.
