### ISSUE TITLE
Papercut fatal error windows 7

### ISSUE THREAD

**Issue by Tazor93** [ChangemakerStudios/Papercut#92]
Hi,
when i try to launch papercut (last version) i have the following error :+1: 

> {"Timestamp":"2018-01-22T17:44:02.0000122+01:00","Level":"Fatal","MessageTemplate":"Unhandled Exception","Exception":"Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MainView[] (DelegateActivator), Services = [System.Collections.Generic.IEnumerable`1[[Papercut.Views.MainView, Papercut, Version=5.1.3.0, Culture=neutral, PublicKeyToken=null]]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MainView (ReflectionActivator), Services = [System.Windows.Media.Composition.DUCE+IResource, System.Windows.Media.Animation.IAnimatable, System.Windows.IInputElement, System.Windows.IFrameworkInputElement, System.ComponentModel.ISupportInitialize, System.Windows.Markup.IHaveResources, System.Windows.Markup.IQueryAmbient, System.Windows.Markup.IAddChild, System.Windows.IWindowService, System.Windows.Markup.IComponentConnector, Papercut.Views.MainView], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'MainView'. ---> L'invocation du constructeur sur le type 'TheArtOfDev.HtmlRenderer.WPF.HtmlPanel' qui correspond aux contraintes de liaison spécifiées a levé une exception. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = MainView (ReflectionActivator), Services = [System.Windows.Media.Composition.DUCE+IResource, System.Windows.Media.Animation.IAnimatable, System.Windows.IInputElement, System.Windows.IFrameworkInputElement, System.ComponentModel.ISupportInitialize, System.Windows.Markup.IHaveResources, System.Windows.Markup.IQueryAmbient, System.Windows.Markup.IAddChild, System.Windows.IWindowService, System.Windows.Markup.IComponentConnector, Papercut.Views.MainView], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor()' on type 'MainView'. ---> L'invocation du constructeur sur le type 'TheArtOfDev.HtmlRenderer.WPF.HtmlPanel' qui correspond aux contraintes de liaison spécifiées a levé une exception. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor()' on type 'MainView'. ---> L'invocation du constructeur sur le type 'TheArtOfDev.HtmlRenderer.WPF.HtmlPanel' qui correspond aux contraintes de liaison spécifiées a levé une exception. (See inner exception for details.) ---> System.Windows.Markup.XamlParseException: L'invocation du constructeur sur le type 'TheArtOfDev.HtmlRenderer.WPF.HtmlPanel' qui correspond aux contraintes de liaison spécifiées a levé une exception. ---> System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'TheArtOfDev.HtmlRenderer.WPF.Adapters.WpfAdapter'. ---> System.TypeInitializationException: Une exception a été levée par l'initialiseur de type pour 'System.Windows.Media.Fonts'. ---> System.IO.FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1 ---> System.IO.FileFormatException: No FontFamily element found in FontFamilyCollection that matches current OS or greater: Windows7SP1\r\n   à MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)\r\n   à MS.Internal.FontFace.CompositeFontParser.ParseFontFamilyCollectionElement()\r\n   à MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)\r\n   --- Fin de la trace de la pile d'exception interne ---\r\n   à MS.Internal.FontFace.CompositeFontParser.Fail(String message, Exception innerException)\r\n   à MS.Internal.FontFace.CompositeFontParser..ctor(Stream fileStream)\r\n   à MS.Internal.FontCache.FamilyCollection.SystemCompositeFonts.GetCompositeFontFamilyAtIndex(Int32 index)\r\n   à MS.Internal.FontCache.FamilyCollection.GetFontFamilies(Uri fontFamilyBaseUri, String fontFamilyLocationReference)\r\n   à System.Windows.Media.Fonts.CreateFamilyCollection(Uri fontLocation, Uri fontFamilyBaseUri, String fontFamilyLocationReference)\r\n   à System.Windows.Media.Fonts..cctor()\r\n   --- Fin de la trace de la pile d'exception interne ---\r\n   à TheArtOfDev.HtmlRenderer.WPF.Adapters.WpfAdapter..ctor() dans d:\\source\\github\\HTML-Renderer\\Source\\HtmlRenderer.WPF\\Adapters\\WpfAdapter.cs:ligne 62\r\n   à TheArtOfDev.HtmlRenderer.WPF.Adapters.WpfAdapter..cctor() dans d:\\source\\github\\HTML-Renderer\\Source\\HtmlRenderer.WPF\\Adapters\\WpfAdapter.cs:ligne 37\r\n   --- Fin de la trace de la pile d'exception interne ---\r\n   à TheArtOfDev.HtmlRenderer.WPF.Adapters.WpfAdapter.get_Instance()\r\n   à TheArtOfDev.HtmlRenderer.WPF.HtmlContainer..ctor() dans d:\\source\\github\\HTML-Renderer\\Source\\HtmlRenderer.WPF\\HtmlContainer.cs:ligne 51\r\n   à TheArtOfDev.HtmlRenderer.WPF.HtmlControl..ctor() dans d:\\source\\github\\HTML-Renderer\\Source\\HtmlRenderer.WPF\\HtmlControl.cs:ligne 102\r\n   à TheArtOfDev.HtmlRenderer.WPF.HtmlPanel..ctor() dans d:\\source\\github\\HTML-Renderer\\Source\\HtmlRenderer.WPF\\HtmlPanel.cs:ligne 61\r\n   --- Fin de la trace de la pile d'exception interne ---\r\n   à System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)\r\n   à System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)\r\n   à System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)\r\n   à System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)\r\n   à lambda_method(Closure , Object[] )\r\n   à Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n   --- Fin de la trace de la pile d'exception interne ---\r\n   à Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()\r\n   à Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n   à Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n   --- Fin de la trace de la pile d'exception interne ---\r\n   à Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n   à Autofac.Core.Resolving.InstanceLookup.Execute()\r\n   à Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n   à System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()\r\n   à System.Linq.Buffer`1..ctor(IEnumerable`1 source)\r\n   à System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)\r\n   à Autofac.Features.Collections.CollectionRegistrationSource.<>c__DisplayClass0_0.<RegistrationsFor>b__0(IComponentContext c, IEnumerable`1 p)\r\n   à Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)\r\n   à Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n   --- Fin de la trace de la pile d'exception interne ---\r\n   à Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)\r\n   à Autofac.Core.Resolving.InstanceLookup.Execute()\r\n   à Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)\r\n   à Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)\r\n   à Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)\r\n   à Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)\r\n   à Papercut.AppBootstrapper.GetAllInstances(Type service)\r\n   à Caliburn.Micro.ViewLocator.<>c.<.cctor>b__10_0(Type viewType)\r\n   à Caliburn.Micro.ViewLocator.<>c.<.cctor>b__10_8(Object model, DependencyObject displayLocation, Object context)\r\n   à Caliburn.Micro.WindowManager.CreateWindow(Object rootModel, Boolean isDialog, Object context, IDictionary`2 settings)\r\n   à Caliburn.Micro.WindowManager.ShowWindow(Object rootModel, Object context, IDictionary`2 settings)\r\n   à Papercut.AppBootstrapper.OnStartup(Object sender, StartupEventArgs e)\r\n   à System.Windows.Application.OnStartup(StartupEventArgs e)\r\n   à Papercut.App.OnStartup(StartupEventArgs e)\r\n   à System.Windows.Application.<.ctor>b__1_0(Object unused)\r\n   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\r\n   à System.Windows.Threading.DispatcherOperation.InvokeImpl()\r\n   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)\r\n   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   à MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)\r\n   à System.Windows.Threading.DispatcherOperation.Invoke()\r\n   à System.Windows.Threading.Dispatcher.ProcessQueue()\r\n   à System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)\r\n   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)\r\n   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)\r\n   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)\r\n   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)\r\n   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)\r\n   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)\r\n   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)\r\n   à System.Windows.Application.RunDispatcher(Object ignore)\r\n   à System.Windows.Application.RunInternal(Window window)\r\n   à Papercut.App.Main()","Properties":{"MachineName":"FR-PAR1-M02653","Is64BitOperatingSystem":true,"OSVersion":"Microsoft Windows NT 6.1.7601 Service Pack 1","ProcessorCount":12,".NETVersion":"4.0.30319.42000"}}

**Comment by Jaben** [comment]
Microsoft bug. Workaround is here: https://github.com/dotnet/announcements/issues/53

**Comment by Tazor93** [comment]
It works. Tahnks to you
