### ISSUE TITLE
Message Lint

### ISSUE THREAD

**Issue by vasiluy-kondr** [ChangemakerStudios/Papercut#95]
There is [a tool](https://tools.ietf.org/tools/msglint/) for linting message headers. It's [open source](https://tools.ietf.org/tools/msglint/msglint-1.04.tar.gz). Maybe it could be bundled with Papercut somehow.

**Comment by jijiechen** [comment]
Thank you for raising the idea. 
Could you also share what's the benefit if we add this feature?
