### ISSUE TITLE
SVG Images don't show at all

### ISSUE THREAD

**Issue by sphereweb83** [ChangemakerStudios/Papercut#98]
Hello,

I am experiencing issues with SVG images in my email., They don't seem to be shown at all. However the PNG image is shown correctly. Can you help/suggest?

![image](https://user-images.githubusercontent.com/13355895/37248669-47b474e4-24a6-11e8-95ae-710cdbbf3316.png)

**Comment by Jaben** [comment]
More information is needed: what does the email look like? HTML with external links? Internal context links? How does it look in a different client?

**Comment by Deltids** [comment]
I have the same issue. *.svg doesnt show. I use the exact implementations that is used here: http://www.systemnetmail.com/faq/4.4.aspx under [ C# ]. So it is an attached image with <img src=cid:companyLogo> inline html.

**Comment by jimbobmcgee** [comment]
The standard .NET WebBrowser control defaults to rendering in IE7 mode.  I don't *think* IE7 supported SVG.  It is potentially possible to set the rendering mode to IE11, in one of two ways:

 1. Have Papercut code inject a `<meta http-equiv="X-UA-Compatible" content="IE=11"/>` tag into the `<head>` of the HTML that is pushed to the control.  You could also use `IE=edge` to always use the latest render mode (or offer it in a setting/drop-down/etc.)

 2. Add a DWORD value to the Windows Registry with decimal value `11000` into one of the following applicable keys, prior to running the application:
     a. `HKCU\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION` (for the current user)
     b. `HKLM\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BROWSER_EMULATION` (for all users running on 32-bit OS, or running a 64-bit exe)
     c. `HKLM\SOFTWARE\WOW6432Node\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION` (for all users running a 32-bit exe on a 64-bit OS)

Could either @sphereweb83 or @Deltids (or anyone else affected) determine whether the registry 'fix' works as expected, by running the following in a command-prompt:

    reg.exe add "HKCU\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION" /v Papercut.exe /t REG_DWORD /d 11000

...and to undo...

    reg.exe delete "HKCU\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION" /v Papercut.exe

Further details can be found in Rick Stahl's blog: https://weblog.west-wind.com/posts/2011/May/21/Web-Browser-Control-Specifying-the-IE-Version
