### ISSUE TITLE
Windows Defender marks papercut.exe as malware

### ISSUE THREAD

**Issue by obrienmd** [ChangemakerStudios/Papercut#99]
When I try to run the latest release (5.1.19) from the zip archive, Windows warns me that it contains unwanted software. Defender shows the following threat:

Trojan:Win32/Azden.B!cl (Severe)

I'm a bit worried that the release has been modified (downloaded straight from GitHub over HTTPS), is anyone else seeing this?

**Comment by obrienmd** [comment]
I suspect false positive - VirusTotal says the exe file is clean:

https://www.virustotal.com/#/file/988ce1ace4291f984adca80c8760a3b3fc85183ce7dfeabd4b9a6b260387e356/detection

**Comment by davidcruy** [comment]
I received the same message.

I was changing the settings to enable papercut on startup (Windows 10). This triggered Defender.

Trojan:Win32/Azden.B!cl
Alert Level: Severe

startup: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Changemaker Studios\Papercut.lnk
file: C:\Program Files (x86)\Changemaker Studios\Papercut\Papercut.exe

**Comment by Jaben** [comment]
I cannot reproduce this. I just downloaded latest and directly scanned with Defender. Not clue why you guys are getting this error.

**Comment by Jaben** [comment]
Going to disable the Fody Costura bundling ... seems to be causing this issues.

**Comment by Jaben** [comment]
E.g.: https://github.com/Fody/Costura/issues/161

**Comment by Jaben** [comment]
Just released a new version. Note that builds happen on AppVeyor and are directly deployed to Github. Please try this version (5.1.23) and see if it's still reporting Papercut as a Trojan.

**Comment by obrienmd** [comment]
LGTM, no malware false positive on 5.1.23.

Thanks!

**Comment by davidcruy** [comment]
Thank you for your quick support! (and this excellent app)
